name: Autograding Tests

on:
  push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run Autograding Tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: 'Test Name'
        setup-command: 'npm install'
        command: 'npm test'
        timeout: '15'
        max-score: '100'
    - name: Autograding Reporter
      uses: ...